version: "3.8"

services:
  mattermost:
    build: .
    image: my-mattermost:custom
    # Remove client volume mount
    volumes:
      - ./volumes/mattermost-data:/mattermost/data
    # Rest of your existing config...
    # Remove client volume mount
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://${POSTGRES_ROOT_USER}:${POSTGRES_ROOT_PASSWORD}@postgres:5432/${POSTGRES_DB_MATTERMOST}?sslmode=disable
      - MM_ADMIN_USERNAME=${MM_ADMIN_USERNAME}
      - MM_ADMIN_PASSWORD=${MM_ADMIN_PASSWORD}
